apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mgo-rs
  namespace: demo
spec:
  version: "3.6-v1"
  replicas: 5
  replicaSet:
    name: rs0
  storage:
    storageClassName: "rook-ceph-block"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
