apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: snapshot-sharding
  namespace: demo
  labels:
    kubedb.com/kind: MongoDB
spec:
  databaseName: mongo-sh
  storageSecretName: gcs-secret
  gcs:
    bucket: kubedb-qa
