resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: tahsin/git-pull-resource
    tag: latest

resources:
- name: mongodb
  type: git
  source:
    uri: https://github.com/kubedb/mongodb
    branch: concourse

- name: pull-request
  type: pull-request
  source:
    owner: kubedb
    repo: mongodb
    org: appscode
    access_token: ((access_token))

jobs:
- name: test-mongodb
  plan:
  - get: mongodb
    trigger: true
  - task: test-e2e
    file: mongodb/hack/concourse/task.yml
    params:
      TOKEN: ((digitaloceanToken))

- name: test-mongodb-pr
  plan:
  - get: pull-request
    trigger: true
  - put: pull-request
    params: { path: pull-request, status: pending}
  - task: test-e2e
    file: pull-request/hack/concourse/task.yml
    input_mapping:
      mongodb: pull-request
    params:
      TOKEN: ((digitaloceanToken))
    on_success:
      put: pull-request
      params: { path: pull-request, status: success}
    on_failure:
      put: pull-request
      params: {path: pull-request, status: failure}
