resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: tahsin/git-pull-resource
    tag: latest

resources:
- name: mongodb
  type: git
  source:
    uri: https://github.com/kubedb/mongodb
    branch: concourse

- name: pull-request
  type: pull-request
  source:
    owner: kubedb
    repo: mongodb
    org: appscode
    access_token: ((access_token))

- name: creds
  type: s3
  source:
    bucket: kubedbci
    access_key_id: ((s3-access-key))
    secret_access_key: ((s3-secret))
    versioned_file: gcs.zip

jobs:
- name: test-mongodb
  plan:
  - get: mongodb
    trigger: true
  - get: creds
    params:
      unpack: true
  - task: test-e2e
    privileged: true
    file: mongodb/hack/concourse/task.yml
    params:
      TOKEN: ((digitaloceanToken))
      DOCKER_USER: ((docker_user))
      DOCKER_PASS: ((docker_pass))
      AWS_KEY_ID: ((aws_key_id))
      AWS_SECRET: ((aws_secret))
      GCE_PROJECT_ID: ((gce_project_id))
      AZURE_ACCOUNT_NAME: ((azure_account_name))
      AZURE_ACCOUNT_KEY: ((azure_account_key))
      AZURE_BUCKET_NAME: ((azure_bucket_name))
      S3_BUCKET_NAME: ((s3_bucket_name))
      GCS_BUCKET_NAME: ((gcs_bucket_name))

- name: test-mongodb-pr
  plan:
  - get: pull-request
    trigger: true
  - put: pull-request
    params: { path: pull-request, status: pending}
  - get: creds
    params:
      unpack: true
  - task: test-e2e
    privileged: true
    file: pull-request/hack/concourse/task.yml
    input_mapping:
      mongodb: pull-request
    params:
      TOKEN: ((digitaloceanToken))
      DOCKER_USER: ((docker_user))
      DOCKER_PASS: ((docker_pass))
      AWS_KEY_ID: ((aws_key_id))
      AWS_SECRET: ((aws_secret))
      AZURE_BUCKET_NAME: ((azure_bucket_name))
      GCE_PROJECT_ID: ((gce_project_id))
      AZURE_ACCOUNT_NAME: ((azure_account_name))
      S3_BUCKET_NAME: ((s3_bucket_name))
      GCS_BUCKET_NAME: ((gcs_bucket_name))
    on_success:
      put: pull-request
      params: { path: pull-request, status: success}
    on_failure:
      put: pull-request
      params: {path: pull-request, status: failure}
